
INCFLAGS += -Iexternal/libjpeg-turbo -Iexternal/libjpeg-turbo/vcproj -Iexternal/libjpeg-turbo/win
CFLAGS += -DNO_STRICT -DHAVE_CONFIG_H -DUSE_ALLOCA -DHAVE_LRINTF -DHAVE_LRINT -DFLOAT_APPROX

LIBJPEG_SOURCES += external/libjpeg-turbo/jaricom.c external/libjpeg-turbo/jcapimin.c external/libjpeg-turbo/jcapistd.c external/libjpeg-turbo/jcarith.c external/libjpeg-turbo/jccoefct.c external/libjpeg-turbo/jccolor.c external/libjpeg-turbo/jcdctmgr.c external/libjpeg-turbo/jchuff.c external/libjpeg-turbo/jcinit.c external/libjpeg-turbo/jcmainct.c external/libjpeg-turbo/jcmarker.c external/libjpeg-turbo/jcmaster.c external/libjpeg-turbo/jcomapi.c external/libjpeg-turbo/jcparam.c external/libjpeg-turbo/jcphuff.c external/libjpeg-turbo/jcprepct.c external/libjpeg-turbo/jcsample.c external/libjpeg-turbo/jctrans.c external/libjpeg-turbo/jdapimin.c external/libjpeg-turbo/jdapistd.c external/libjpeg-turbo/jdarith.c external/libjpeg-turbo/jdatadst-tj.c external/libjpeg-turbo/jdatadst.c external/libjpeg-turbo/jdatasrc-tj.c external/libjpeg-turbo/jdatasrc.c external/libjpeg-turbo/jdcoefct.c external/libjpeg-turbo/jdcolor.c external/libjpeg-turbo/jddctmgr.c external/libjpeg-turbo/jdhuff.c external/libjpeg-turbo/jdinput.c external/libjpeg-turbo/jdmainct.c external/libjpeg-turbo/jdmarker.c external/libjpeg-turbo/jdmaster.c external/libjpeg-turbo/jdmerge.c external/libjpeg-turbo/jdphuff.c external/libjpeg-turbo/jdpostct.c external/libjpeg-turbo/jdsample.c external/libjpeg-turbo/jdtrans.c external/libjpeg-turbo/jerror.c external/libjpeg-turbo/jfdctflt.c external/libjpeg-turbo/jfdctfst.c external/libjpeg-turbo/jfdctint.c external/libjpeg-turbo/jidctflt.c external/libjpeg-turbo/jidctfst.c external/libjpeg-turbo/jidctint.c external/libjpeg-turbo/jidctred.c external/libjpeg-turbo/jmemmgr.c external/libjpeg-turbo/jmemnobs.c external/libjpeg-turbo/jquant1.c external/libjpeg-turbo/jquant2.c external/libjpeg-turbo/jutils.c external/libjpeg-turbo/transupp.c external/libjpeg-turbo/turbojpeg.c
LIBJPEG_SIMD_SOURCES += external/libjpeg-turbo/jsimd_none.c
# LIBJPEG_SIMD_SOURCES += external/libjpeg-turbo/simd/jccolor-mmx.asm external/libjpeg-turbo/simd/jccolor-sse2.asm external/libjpeg-turbo/simd/jcgray-mmx.asm external/libjpeg-turbo/simd/jcgray-sse2.asm external/libjpeg-turbo/simd/jchuff-sse2.asm external/libjpeg-turbo/simd/jcsample-mmx.asm external/libjpeg-turbo/simd/jcsample-sse2.asm external/libjpeg-turbo/simd/jdcolor-mmx.asm external/libjpeg-turbo/simd/jdcolor-sse2.asm external/libjpeg-turbo/simd/jdmerge-mmx.asm external/libjpeg-turbo/simd/jdmerge-sse2.asm external/libjpeg-turbo/simd/jdsample-mmx.asm external/libjpeg-turbo/simd/jdsample-sse2.asm external/libjpeg-turbo/simd/jfdctflt-3dn.asm external/libjpeg-turbo/simd/jfdctflt-sse.asm external/libjpeg-turbo/simd/jfdctfst-mmx.asm external/libjpeg-turbo/simd/jfdctfst-sse2.asm external/libjpeg-turbo/simd/jfdctint-mmx.asm external/libjpeg-turbo/simd/jfdctint-sse2.asm external/libjpeg-turbo/simd/jidctflt-3dn.asm external/libjpeg-turbo/simd/jidctflt-sse.asm external/libjpeg-turbo/simd/jidctflt-sse2.asm external/libjpeg-turbo/simd/jidctfst-mmx.asm external/libjpeg-turbo/simd/jidctfst-sse2.asm external/libjpeg-turbo/simd/jidctint-mmx.asm external/libjpeg-turbo/simd/jidctint-sse2.asm external/libjpeg-turbo/simd/jidctred-mmx.asm external/libjpeg-turbo/simd/jidctred-sse2.asm external/libjpeg-turbo/simd/jquant-3dn.asm external/libjpeg-turbo/simd/jquant-mmx.asm external/libjpeg-turbo/simd/jquant-sse.asm external/libjpeg-turbo/simd/jquantf-sse2.asm external/libjpeg-turbo/simd/jquanti-sse2.asm external/libjpeg-turbo/simd/jsimdcpu.asm

SOURCES += dllmain.cpp LoadJPEG.cpp
SOURCES += $(LIBJPEG_SOURCES) $(LIBJPEG_SIMD_SOURCES)

PROJECT_BASENAME = krglhjpeg

include external/tp_stubz/Rules.lib.make
